# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: surface.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsurface.proto\x12\x07surface\"#\n\x0fGetPaperRequest\x12\x10\n\x08\x63orpusid\x18\x01 \x01(\t\"1\n\x10GetPaperResponse\x12\x1d\n\x05paper\x18\x01 \x01(\x0b\x32\x0e.surface.Paper\"3\n\x12InsertPaperRequest\x12\x1d\n\x05paper\x18\x01 \x01(\x0b\x32\x0e.surface.Paper\"\'\n\x13InsertPaperResponse\x12\x10\n\x08\x63orpusid\x18\x01 \x01(\t\"@\n\x12SearchPaperRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x04\x12\x0c\n\x04topK\x18\x03 \x01(\x04\"5\n\x13SearchPaperResponse\x12\x1e\n\x06papers\x18\x01 \x03(\x0b\x32\x0e.surface.Paper\"Q\n\x0b\x45xternalids\x12\x0b\n\x03mag\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63l\x18\x02 \x01(\t\x12\x0b\n\x03\x64oi\x18\x03 \x01(\t\x12\x0c\n\x04pmid\x18\x04 \x01(\t\x12\r\n\x05\x61rxiv\x18\x05 \x01(\t\"i\n\x0eOpenAccessInfo\x12)\n\x0b\x65xternalids\x18\x01 \x01(\x0b\x32\x14.surface.Externalids\x12\x0f\n\x07license\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x8e\x01\n\x05Paper\x12\x10\n\x08\x63orpusid\x18\x01 \x01(\t\x12/\n\x0eopenaccessinfo\x18\x02 \x01(\x0b\x32\x17.surface.OpenAccessInfo\x12\x10\n\x08\x61\x62stract\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x10\n\x08\x66ulltext\x18\x05 \x01(\t\x12\x0f\n\x07updated\x18\x06 \x01(\t\",\n\x08PaperVec\x12\x10\n\x08\x63orpusid\x18\x01 \x01(\x04\x12\x0e\n\x06vector\x18\x02 \x01(\x0c\x32\xe8\x01\n\x0bPaperSearch\x12\x41\n\x08GetPaper\x12\x18.surface.GetPaperRequest\x1a\x19.surface.GetPaperResponse\"\x00\x12J\n\x0bInsertPaper\x12\x1b.surface.InsertPaperRequest\x1a\x1c.surface.InsertPaperResponse\"\x00\x12J\n\x0bSearchPaper\x12\x1b.surface.SearchPaperRequest\x1a\x1c.surface.SearchPaperResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surface_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPAPERREQUEST._serialized_start=26
  _GETPAPERREQUEST._serialized_end=61
  _GETPAPERRESPONSE._serialized_start=63
  _GETPAPERRESPONSE._serialized_end=112
  _INSERTPAPERREQUEST._serialized_start=114
  _INSERTPAPERREQUEST._serialized_end=165
  _INSERTPAPERRESPONSE._serialized_start=167
  _INSERTPAPERRESPONSE._serialized_end=206
  _SEARCHPAPERREQUEST._serialized_start=208
  _SEARCHPAPERREQUEST._serialized_end=272
  _SEARCHPAPERRESPONSE._serialized_start=274
  _SEARCHPAPERRESPONSE._serialized_end=327
  _EXTERNALIDS._serialized_start=329
  _EXTERNALIDS._serialized_end=410
  _OPENACCESSINFO._serialized_start=412
  _OPENACCESSINFO._serialized_end=517
  _PAPER._serialized_start=520
  _PAPER._serialized_end=662
  _PAPERVEC._serialized_start=664
  _PAPERVEC._serialized_end=708
  _PAPERSEARCH._serialized_start=711
  _PAPERSEARCH._serialized_end=943
# @@protoc_insertion_point(module_scope)
